# -*- coding: utf-8 -*-
"""Prueba Técnica_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bc6ztrslitxWyHXva96cwLTH2E0ch9Ni

# Punto N°1: Carga de Información

Cargar un data set, realizar el cargue y depuración del archivo OFEI1204.txt.
Se debe entregar una tabla con las columnas:



*   Agente
*   Planta
*   Hora_1
*   Hora_2
*   Hora_3
*   ...
*   Hora_24


***Solamente procesar los registros Tipo D.***
"""

import pandas as pd
import requests
from io import StringIO

# URL del archivo en el repositorio de GitHub
url = 'https://raw.githubusercontent.com/Merxxotas/Prueba-DataKnow/main/Prueba_Tecnica/Datos3/OFEI1204.txt'

# Descargar el archivo
response = requests.get(url)
response.raise_for_status()  # Asegúrate de que la solicitud fue exitosa

# Guardar el contenido del archivo en una variable
file_content = response.text

data_frame = pd.read_table(StringIO(file_content), encoding='utf-8', header=None, skip_blank_lines=True)
old_data_frame = data_frame

# Visualización de los datos
print(data_frame)

# Detalle de los datos
print(data_frame.describe(include='all'))

# Separar los datos de las líneas relevantes
filtered_rows = []
current_agent = None

for _, row in data_frame.iterrows():
    line = row[0].strip()  # Trabajar con la columna única cargada como texto
    if line.startswith("AGENTE: "):
        current_agent = line.replace("AGENTE: ", "").strip()
    elif ', D, ' in line:
        parts = line.split(', ')
        planta = parts[0].strip()
        tipo = parts[1].strip()
        horas = [float(h.strip()) for h in parts[2:]]
        filtered_rows.append([current_agent, planta] + horas)

# Crear un DataFrame con las filas filtradas
columns = ['Agente', 'Planta'] + [f'Hora_{i}' for i in range(1, 25)]
df = pd.DataFrame(filtered_rows, columns=columns)

# Visualizar resultados
print(df.head())

# Guardar la tabla resultante en formato CSV
output_path = 'Tabla_Resultante.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Cargar el archivo .CSV generado
loaded_data = pd.read_csv(output_path, encoding='utf-8')

# Visualización de los datos
print(loaded_data.head())

# Mostrar solo las primeras 15 filas con estilo aplicado
df.head(15).style.format(precision=2).highlight_max(axis=0, color='gray').highlight_min(axis=0, color='black')